### ISSUE TITLE
Button to turn on / off boost for a certain zone

### ISSUE THREAD

**Issue by jensolsson** [rmassch/healthbox-hacs#124]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Thanks for a great integration

Trying to create a button for room boost. Is this possible?
Seem i can run a boost action using automation but having a button to turn on and off boost seem to not work. 
Is this possible to achieve with the current version?

### Describe the solution you'd like

To have button to turn boost on / off

### Describe alternatives you've considered

None

### Additional context

None

**Comment by rmassch** [comment]
I basically made a script for this and call the script from a button
Here's my script. The input booleans are sliders I can set, or you can use fixed values if you like.

If you use fixed values you probably don't even need the script and could call the action directly as you can see in the hold_action below (provided you add boost_level and boost_timeout to the data dictionary)

Let me know if this helps or if you have any further questions

Script:
```yaml
alias: Boost Healthbox Room
sequence:
  - data:
      device_id: "{{ device_id }}"
      boost_level: "{{ states('input_number.hb3_boost_level') | int }}"
      boost_timeout: "{{ states('input_select.hb3_boost_time') | int }}"
    action: healthbox.start_room_boost
mode: queued
icon: mdi:fan-alert
```

Button:
```yaml
      - type: custom:mushroom-entity-card
        entity: sensor.office_airflow_ventilation_rate
        name: Office
        icon: mdi:desk
        icon_color: purple
        tap_action:
          confirmation:
            text: Are you sure you want to enable the ventilation boost?
          action: call-service
          service: script.boost_healthbox_room
          target: {}
          data:
            device_id: 41cb4148946ded6558c007dcc5b0d037
        hold_action:
          confirmation:
            text: Are you sure you want to cancel the boost?
          action: call-service
          service: healthbox.stop_room_boost
          data:
            device_id: 41cb4148946ded6558c007dcc5b0d037
          target: {}
```
