### ISSUE TITLE
Error while setting up healthbox platform for sensor

### ISSUE THREAD

**Issue by davidvf** [rmassch/healthbox-hacs#24]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

During the setup of this integration `v0.0.7-alpha` I got the following error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/healthbox/sensor.py", line 216, in async_setup_entry
    room_sensors = generate_room_sensors_for_healthbox(coordinator=coordinator)
  File "/config/custom_components/healthbox/sensor.py", line 98, in generate_room_sensors_for_healthbox
    if room.indoor_co2_concentration is not None:
  File "/usr/local/lib/python3.10/site-packages/pyhealthbox3/models.py", line 76, in indoor_co2_concentration
    co2_concentration = [
  File "/usr/local/lib/python3.10/site-packages/pyhealthbox3/models.py", line 77, in <listcomp>
    sensor["parameter"]["concentration"]["value"]
KeyError: 'concentration'
```

If i remove the API key, the healthbox is created successfully, but without the additional sensors like temperature, humidity, ...

```
device_type: HEALTHBOX3
description: Healthbox 3.0
serial: xxxxxxx
warranty_number: KML451310013A06
global:
  parameter:
    device name:
      unit: ''
      value: 'HEALTHBOX3[KML451310013A06]'
    legislation country:
      unit: ''
      value: be
    warranty:
      unit: ''
      value: KML451310013A06
room:
  '1':
    name: Slaapkamer Mille
    type: BedRoom
    parameter:
      doors_open:
        unit: ''
        value: false
      doors_present:
        unit: ''
        value: false
      icon:
        unit: ''
        value: ''
      measured_power:
        unit: ''
        value: 0
      measured_voltage:
        unit: ''
        value: 0
      measurement:
        unit: ''
        value: 34.2
      offset:
        unit: ''
        value: -5
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '1'
      valve_warranty:
        unit: ''
        value: KRP833050000B69
      nominal:
        unit: m³/h
        value: 31
    profile_name: health
    actuator:
      - name: 'air valve[1]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 1
        parameter:
          flow_rate:
            unit: m³/h
            value: 8.959410865747063
    sensor:
      - basic_id: 1
        name: 'indoor temperature[1]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 15.122453650720992
        type: indoor temperature
      - basic_id: 1
        name: 'indoor relative humidity[1]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 75.27122911421378
        type: indoor relative humidity
      - basic_id: 1
        name: 'indoor CO2[1]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 625
        type: indoor CO2
      - basic_id: 1
        name: 'indoor air quality index[1]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 72.3545012888952
          main_pollutant:
            unit: ''
            value: indoor relative humidity
        type: indoor air quality index
  '2':
    name: Slaapkamer
    type: BedRoom
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 35
      offset:
        unit: ''
        value: -2
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '2'
      valve_warranty:
        unit: ''
        value: KHN675040000O51
      nominal:
        unit: m³/h
        value: 30
    profile_name: health
    actuator:
      - name: 'air valve[2]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 2
        parameter:
          flow_rate:
            unit: m³/h
            value: 4.666666666666667
    sensor:
      - basic_id: 2
        name: 'indoor temperature[2]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 15.8567940794995
        type: indoor temperature
      - basic_id: 2
        name: 'indoor relative humidity[2]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 73.6614023041123
        type: indoor relative humidity
      - basic_id: 2
        name: 'indoor CO2[2]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 657
        type: indoor CO2
      - basic_id: 2
        name: 'indoor air quality index[2]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 64.3788966589213
          main_pollutant:
            unit: ''
            value: indoor relative humidity
        type: indoor air quality index
  '3':
    name: Keuken (open)
    type: Kitchen
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 80
      offset:
        unit: ''
        value: 0
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '3'
      valve_warranty:
        unit: ''
        value: XUD025970004F51
      nominal:
        unit: m³/h
        value: 75
    profile_name: health
    actuator:
      - name: 'air valve[3]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 3
        parameter:
          flow_rate:
            unit: m³/h
            value: 7.5
    sensor:
      - basic_id: 3
        name: 'indoor temperature[3]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 16.676585030899517
        type: indoor temperature
      - basic_id: 3
        name: 'indoor relative humidity[3]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 67.55168993667506
        type: indoor relative humidity
      - basic_id: 3
        name: 'indoor air quality index[3]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 37.51763653052737
          main_pollutant:
            unit: ''
            value: ''
        type: indoor air quality index
      - basic_id: 3
        name: 'indoor CO2[3]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 612
        type: indoor CO2
  '4':
    name: Toilet glvl
    type: Toilet
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 29.4
      offset:
        unit: ''
        value: -3
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '4.1'
      valve_warranty:
        unit: ''
        value: KCR338090000G53
      nominal:
        unit: m³/h
        value: 25
    profile_name: health
    actuator:
      - name: 'air valve[41]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 41
        parameter:
          flow_rate:
            unit: m³/h
            value: 4.4
    sensor:
      - basic_id: 41
        name: 'indoor temperature[41]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 16.11047531853208
        type: indoor temperature
      - basic_id: 41
        name: 'indoor relative humidity[41]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 79.0051117723354
        type: indoor relative humidity
      - basic_id: 41
        name: 'indoor volatile organic compounds[41]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 1285.2090155511903
          concentration_maximum:
            unit: ppm
            value: 1323.9497895536988
          raw:
            unit: ppm
            value: 53684
        type: indoor volatile organic compounds
      - basic_id: 41
        name: 'indoor air quality index[41]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 29.22222222222222
          main_pollutant:
            unit: ''
            value: ''
        type: indoor air quality index
  '5':
    name: Toilet verdiep
    type: Toilet
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 27.7
      offset:
        unit: ''
        value: 0
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '4.2'
      valve_warranty:
        unit: ''
        value: KML007780000O60
      nominal:
        unit: m³/h
        value: 25
    profile_name: health
    actuator:
      - name: 'air valve[42]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 42
        parameter:
          flow_rate:
            unit: m³/h
            value: 5
    sensor:
      - basic_id: 42
        name: 'indoor temperature[42]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 16.00900282291905
        type: indoor temperature
      - basic_id: 42
        name: 'indoor relative humidity[42]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 70.38071259632258
        type: indoor relative humidity
      - basic_id: 42
        name: 'indoor volatile organic compounds[42]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 450
          concentration_maximum:
            unit: ppm
            value: 512.0944000000018
          raw:
            unit: ppm
            value: 47021
        type: indoor volatile organic compounds
      - basic_id: 42
        name: 'indoor air quality index[42]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 30.55555555555556
          main_pollutant:
            unit: ''
            value: ''
        type: indoor air quality index
  '6':
    name: Wasplaats
    type: LaundryRoom
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 53.5
      offset:
        unit: ''
        value: -3
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '4.3'
      valve_warranty:
        unit: ''
        value: KHN895980000G45
      nominal:
        unit: m³/h
        value: 50
    profile_name: health
    actuator:
      - name: 'air valve[43]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 43
        parameter:
          flow_rate:
            unit: m³/h
            value: 4.699999999999999
    sensor:
      - basic_id: 43
        name: 'indoor temperature[43]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 16.441596093690393
        type: indoor temperature
      - basic_id: 43
        name: 'indoor relative humidity[43]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 68.22003509575036
        type: indoor relative humidity
      - basic_id: 43
        name: 'indoor CO2[43]_HealthBox 3[Healthbox3]'
        parameter: {}
        type: indoor CO2
      - basic_id: 43
        name: 'indoor air quality index[43]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 40.08821410157669
          main_pollutant:
            unit: ''
            value: indoor relative humidity
        type: indoor air quality index
  '7':
    name: Bureau
    type: BedRoom
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 33
      offset:
        unit: ''
        value: 4
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '5'
      valve_warranty:
        unit: ''
        value: KHN675040000O86
      nominal:
        unit: m³/h
        value: 30
    profile_name: health
    actuator:
      - name: 'air valve[5]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 5
        parameter:
          flow_rate:
            unit: m³/h
            value: 5.666666666666666
    sensor:
      - basic_id: 5
        name: 'indoor temperature[5]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 16.516365300984205
        type: indoor temperature
      - basic_id: 5
        name: 'indoor relative humidity[5]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 69.90768291752498
        type: indoor relative humidity
      - basic_id: 5
        name: 'indoor CO2[5]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 678
        type: indoor CO2
      - basic_id: 5
        name: 'indoor air quality index[5]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 45.76289808643459
          main_pollutant:
            unit: ''
            value: indoor relative humidity
        type: indoor air quality index
  '8':
    name: Badkamer met toilet
    type: BathRoom
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 53
      offset:
        unit: ''
        value: 1
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '6'
      valve_warranty:
        unit: ''
        value: KHN675010000G35
      nominal:
        unit: m³/h
        value: 50
    profile_name: health
    actuator:
      - name: 'air valve[6]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 6
        parameter:
          flow_rate:
            unit: m³/h
            value: 49.35186558873776
    sensor:
      - basic_id: 6
        name: 'indoor temperature[6]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 18.038452735179675
        type: indoor temperature
      - basic_id: 6
        name: 'indoor relative humidity[6]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 77.73708705271991
        type: indoor relative humidity
      - basic_id: 6
        name: 'indoor volatile organic compounds[6]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 450
          concentration_maximum:
            unit: ppm
            value: 450
          raw:
            unit: ppm
            value: 49264
        type: indoor volatile organic compounds
      - basic_id: 6
        name: 'indoor air quality index[6]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 85.92307327070132
          main_pollutant:
            unit: ''
            value: indoor relative humidity
        type: indoor air quality index
  '9':
    name: Slaapkamer Emma
    type: BedRoom
    parameter:
      icon:
        unit: ''
        value: ''
      measurement:
        unit: ''
        value: 33.5
      offset:
        unit: ''
        value: -5
      subzone:
        unit: ''
        value: |
          []
      valve:
        unit: ''
        value: '7'
      valve_warranty:
        unit: ''
        value: I93041820000I19
      nominal:
        unit: m³/h
        value: 30
    profile_name: health
    actuator:
      - name: 'air valve[7]_HealthBox 3[Healthbox3]'
        type: air valve
        basic_id: 7
        parameter:
          flow_rate:
            unit: m³/h
            value: 4.166666666666667
    sensor:
      - basic_id: 7
        name: 'indoor temperature[7]_HealthBox 3[Healthbox3]'
        parameter:
          temperature:
            unit: deg C
            value: 17.286083984375004
        type: indoor temperature
      - basic_id: 7
        name: 'indoor relative humidity[7]_HealthBox 3[Healthbox3]'
        parameter:
          humidity:
            unit: pct
            value: 67.61602783203125
        type: indoor relative humidity
      - basic_id: 7
        name: 'indoor CO2[7]_HealthBox 3[Healthbox3]'
        parameter:
          concentration:
            unit: ppm
            value: 646
        type: indoor CO2
      - basic_id: 7
        name: 'indoor air quality index[7]_HealthBox 3[Healthbox3]'
        parameter:
          index:
            unit: ''
            value: 37.75646831934272
          main_pollutant:
            unit: ''
            value: ''
        type: indoor air quality index
sensor:
  - name: global air quality index
    type: global air quality index
    basic_id: 0
    parameter:
      index:
        unit: ''
        value: 86.20874428548811
      main_pollutant:
        unit: ''
        value: indoor relative humidity
      room:
        unit: ''
        value: Badkamer met toilet
```

### Reproduction steps

1.
2.
3.
...
