### ISSUE TITLE
Start Room Boost

### ISSUE THREAD

**Issue by matt7py** [rmassch/healthbox-hacs#44]
### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/rmassch/healthbox3/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi 
Thank you for this great integration.

I attempted to adjust the fan level for one of the rooms but was unsuccessful. Could you please guide me on how to add it as a card to the dashboard? Additionally, changing the state in the Developer Tools doesn't seem to be working.

![2023-05-30 19_03_26-Settings – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/bdf67a9a-99c0-4d02-b036-507ca7bfb688) 

![2023-05-30 19_10_14-Developer Tools – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/0f824734-0246-45a0-999f-9cfb8e78f373)

**Comment by rmassch** [comment]
Hi @matt7py,

If you want to boost a specific room you have to call a service with the correct properties.
You can test this by using the Developer Tools and using the Services tab as shown below.

Just select the room, choose to what percentage you want to boost (or slow down) and for how long.

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/e6d9aa4b-50d0-444d-957d-7e085fb9c6ee)

If you want to do this through a card it's basically dealer's choice on how you want to pass those parameters. You can use helpers, use fixed values etc but in the end it all comes down to having a button call a service.

Let me know if this helps

**Comment by rmassch** [comment]
Hi @matt7py 

Can you copy the code from your entire card configuration so that I can view it in it's entirety?
(I only need the specific card, not the entire stack)

**Comment by matt7py** [comment]
```
type: horizontal-stack
cards:
  - type: custom:mushroom-fan-card
    icon_animation: true
    fill_container: false
    layout: horizontal
    secondary_info: state
    primary_info: name
    icon_type: icon
    show_percentage_control: true
    show_oscillate_control: false
    collapsible_controls: false
    tap_action:
      action: call-service
      service: healthbox.start_room_boost
      target: {}
      data:
        device_id: 258e93df914e790b39dbf3deaf2ed7be
        boost_level: '{{ states(''input_number.fan_slider'') | int }}'
        boost_timeout: 180
    name: 'Ventilation '
    double_tap_action:
      action: none
    hold_action:
      action: none
    entity: sensor.keuken_open_boost_level_2
```

**Comment by rmassch** [comment]
I'll try to do something similar and let you know how it goes.
Might take a while since my healthbox currently doesn't want to authenticate to Renson's API at the moment.

I'll keep you posted!

**Comment by rmassch** [comment]
Hi @matt7py 

I checked how I did this and instead of calling the state in my service I used a script. For some reason the cards had an issue passing the state as an integer.

Besides that, you can't really use a tap action on a fan card since the tap account is basically for the "fan icon" and not the slider. (I hope this makes sense) I looked into making the boost an actual fan but it's not possible due to limitations in the fan model and the Healthbox not behaving like an actual fan

Below are some snippets I used for my dashboard

Script:
```
alias: Boost Healthbox Room
sequence:
  - service: healthbox.start_room_boost
    data:
      device_id: "{{ device_id }}"
      boost_level: "{{ states('input_number.hb3_boost_level') | int }}"
      boost_timeout: "{{ states('input_select.hb3_boost_tijd') | int }}"
mode: queued
icon: mdi:fan-alert
```

Card:
```
      - type: custom:mushroom-entity-card
        entity: sensor.keuken_open_airflow_ventilation_rate
        name: Keuken
        icon: mdi:food
        icon_color: grey
        tap_action:
          confirmation:
            text: Ben je zeker dat je wil boosten?
          action: call-service
          service: script.boost_healthbox_room
          target: {}
          data:
            device_id: 852c9849c0a77702dfb99bde74e89c77
        hold_action:
          confirmation:
            text: Ben je zeker dat je de boost wil stoppen?
          action: call-service
          service: healthbox.stop_room_boost
          data:
            device_id: 852c9849c0a77702dfb99bde74e89c77
          target: {}
```

Let me know if this helps

**Comment by matt7py** [comment]
I am not an expert in the script, but I followed the steps and there is still a problem that it does not work properly!!

Add script 

![2023-06-14 12_10_04-Settings – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/48ca25bf-0c72-4f2d-9389-051581cd6b31)

Card: 

change the  device_id number to my Keuken device_id
![2023-06-14 12_11_09-Mobile – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/03a55008-892d-45c0-b6eb-e30f73578e30)

Error : 
![2023-06-14 12_13_13-](https://github.com/rmassch/healthbox-hacs/assets/120527800/e237fbbb-64fa-47d9-b37a-958de524f163)

**Comment by rmassch** [comment]
@matt7py 

I think there's an error in your yaml code.
Device_id needs to be on a new line under "data" and indented.

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/0153a05d-9205-48c7-8739-d1edcf6c2a10)

**Comment by matt7py** [comment]
Now I got different error 

![2023-06-14 13_05_00-Mobile – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/b75adb0d-50a2-47ec-83a0-1d11c6b396d9)

Failed to call service script/boost_healthbox_room. Error rendering data template: ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states('input_number.hb3_boost_level') | int }}' but no default was specified

**Comment by rmassch** [comment]
Did you create both these input helpers? 

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/89a246d1-b165-4929-a6d3-bfc8546c7f07)

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/f2c969f8-fe28-4f8e-99fd-785daef943dd)

For example, the input select I use for having presets of amount of minutes

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/b949f70f-63cb-4f7b-b740-4243018cb8bb)

**Comment by matt7py** [comment]
I created the 2 input helpers but still I got problem!! 

![2023-06-14 13_32_50-Settings – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/57c3bf5c-1dac-4ead-aab6-f4b701820c47)


![2023-06-14 13_34_34-Settings – Home Assistant](https://github.com/rmassch/healthbox-hacs/assets/120527800/378e022f-fc0e-4430-9f48-bb4e76f745fc)


error : 

Failed to call service script/boost_healthbox_room. Error rendering data template: ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states('input_number.hb3_boost_level') | int }}' but no default was specified

**Comment by rmassch** [comment]
I think I see what the problem is.

So in Home Assistant you have 2 "names" for an object.
The first is the name (display/friendly name) and the other is the entity id.

If you use code to find a device, in 99.9% of the use cases you'll use the entity id.

In your screenshot I can see you copied my entity id into your name field but Home Assistant automatically adds the object type to the front of the name as the entity id and because of that you end up with the wrong entity id .

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/621872e4-45f9-4d66-bde1-5ceab70f57f9)

So rename the entity id's to this:
`input_select.hb3_boost_tijd`
and
`input_number.hb3_boost_level`

**Comment by matt7py** [comment]
Different error :(

Failed to call service script/boost_healthbox_room. value must be at least 10 for dictionary value @ data['boost_level']

**Comment by matt7py** [comment]
Now it works, thank you.
The question here is how can I control the speed through the slider? Because now become as toggle, I can't control the speed or the time!!

**Comment by rmassch** [comment]
Glad that it's working. We are making progress!

I basically have the input selector and slider in the same vertical stack as my room boosts like in the snippet below.
That way I can select for how long and how hard I want the boost to be. After that I just pick the room I want to boost and off it goes.

![image](https://github.com/rmassch/healthbox-hacs/assets/1083135/89c22fc3-4728-4928-8ba6-e491f905ad07)

Code:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_select.hb3_boost_tijd
        name: Boost Tijd
      - entity: input_number.hb3_boost_level
        name: Boost Level
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: sensor.slaapkamer_r_en_d_airflow_ventilation_rate
        name: Slaapkamer R&D
        icon: mdi:bed
        icon_color: green
        tap_action:
          confirmation:
            text: Ben je zeker dat je wil boosten?
          action: call-service
          service: script.boost_healthbox_room
          target: {}
          data:
            device_id: 4a4f6a693c7e620ca7005766a4657451
        hold_action:
          confirmation:
            text: Ben je zeker dat je de boost wil stoppen?
          action: call-service
          service: healthbox.stop_room_boost
          data:
            device_id: 4a4f6a693c7e620ca7005766a4657451
          target: {}
      - type: custom:mushroom-entity-card
        entity: sensor.bureau_airflow_ventilation_rate
        name: Bureau
        icon: mdi:desk
        icon_color: purple
        tap_action:
          confirmation:
            text: Ben je zeker dat je wil boosten?
          action: call-service
          service: script.boost_healthbox_room
          target: {}
          data:
            device_id: 41cb4196636ded6558c009dcc5b0d037
        hold_action:
          confirmation:
            text: Ben je zeker dat je de boost wil stoppen?
          action: call-service
          service: healthbox.stop_room_boost
          data:
            device_id: 41cb4196636ded6558c009dcc5b0d037
          target: {}
```
